# Form implementation generated from reading ui file 'DownloadSingleVideo.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DownloadSingleVideo(object):
    def setupUi(self, DownloadSingleVideo):
        DownloadSingleVideo.setObjectName("DownloadSingleVideo")
        DownloadSingleVideo.resize(673, 550)
        DownloadSingleVideo.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #D6F4ED\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: #473472;\n"
"    border-radius: 0;\n"
"    color: white\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QComboBox\n"
"{\n"
"    background-color: #87BAC3;\n"
"    color: white;\n"
"    border-radius: 0\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #87BAC3\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=DownloadSingleVideo)
        self.centralwidget.setObjectName("centralwidget")
        self.videourl = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.videourl.setGeometry(QtCore.QRect(90, 10, 311, 22))
        self.videourl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.videourl.setObjectName("videourl")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 21))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 321, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.playerlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.playerlayout.setContentsMargins(0, 0, 0, 0)
        self.playerlayout.setObjectName("playerlayout")
        self.title = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(90, 40, 561, 22))
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setReadOnly(True)
        self.title.setObjectName("title")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 61, 21))
        self.label_3.setObjectName("label_3")
        self.desc = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.desc.setGeometry(QtCore.QRect(20, 250, 631, 91))
        self.desc.setReadOnly(True)
        self.desc.setObjectName("desc")
        self.comments = QtWidgets.QTableView(parent=self.centralwidget)
        self.comments.setGeometry(QtCore.QRect(20, 350, 631, 131))
        self.comments.setStyleSheet("background-color: #53629E;\n"
"color: white")
        self.comments.setObjectName("comments")
        self.downloadbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.downloadbtn.setGeometry(QtCore.QRect(564, 490, 91, 41))
        self.downloadbtn.setObjectName("downloadbtn")
        self.deletebtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deletebtn.setGeometry(QtCore.QRect(20, 490, 91, 41))
        self.deletebtn.setObjectName("deletebtn")
        self.pastebtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pastebtn.setGeometry(QtCore.QRect(590, 11, 61, 20))
        self.pastebtn.setObjectName("pastebtn")
        self.ProgressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.ProgressBar.setGeometry(QtCore.QRect(120, 500, 421, 23))
        self.ProgressBar.setStyleSheet("")
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ProgressBar.setObjectName("ProgressBar")
        self.Quality = QtWidgets.QComboBox(parent=self.centralwidget)
        self.Quality.setGeometry(QtCore.QRect(460, 10, 121, 22))
        self.Quality.setObjectName("Quality")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 10, 41, 21))
        self.label_2.setObjectName("label_2")
        self.singlevideoshowtable = QtWidgets.QTableView(parent=self.centralwidget)
        self.singlevideoshowtable.setGeometry(QtCore.QRect(350, 71, 301, 171))
        self.singlevideoshowtable.setObjectName("singlevideoshowtable")
        self.play_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(170, 220, 171, 20))
        self.play_button.setObjectName("play_button")
        self.time_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(18, 220, 151, 21))
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        DownloadSingleVideo.setCentralWidget(self.centralwidget)

        self.retranslateUi(DownloadSingleVideo)
        QtCore.QMetaObject.connectSlotsByName(DownloadSingleVideo)

    def retranslateUi(self, DownloadSingleVideo):
        _translate = QtCore.QCoreApplication.translate
        DownloadSingleVideo.setWindowTitle(_translate("DownloadSingleVideo", "Elrouby Youtube Downloader: Download Single Video"))
        self.label.setText(_translate("DownloadSingleVideo", "Video URL"))
        self.label_3.setText(_translate("DownloadSingleVideo", "Title"))
        self.downloadbtn.setText(_translate("DownloadSingleVideo", "Download"))
        self.deletebtn.setText(_translate("DownloadSingleVideo", "Delete"))
        self.pastebtn.setText(_translate("DownloadSingleVideo", "Paste"))
        self.label_2.setText(_translate("DownloadSingleVideo", "Quality"))
        self.play_button.setText(_translate("DownloadSingleVideo", "⏸️"))
        self.time_label.setText(_translate("DownloadSingleVideo", "0/0"))
