"""begin yt

Revision ID: 1fa70e4111c9
Revises: 
Create Date: 2025-11-06 17:05:35.497234

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa70e4111c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlistvideos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlistid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('desc', sa.Unicode(), nullable=True),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onevideo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('videoid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('desc', sa.Unicode(), nullable=True),
    sa.Column('img', sa.LargeBinary(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlistvideos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comid', sa.Integer(), nullable=False),
    sa.Column('author', sa.Unicode(), nullable=True),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.Column('likecount', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['onevideo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('onevideo')
    op.drop_table('playlistvideos')
    # ### end Alembic commands ###
