"""begin yt 2

Revision ID: 20d54449afc2
Revises: 1fa70e4111c9
Create Date: 2025-11-06 19:26:07.869954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d54449afc2'
down_revision: Union[str, Sequence[str], None] = '1fa70e4111c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('onevideo', sa.Column('filepath', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('onevideo', 'filepath')
    # ### end Alembic commands ###
