"""begin yt 3

Revision ID: 9ac06f4223a9
Revises: 20d54449afc2
Create Date: 2025-11-06 19:26:57.136860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac06f4223a9'
down_revision: Union[str, Sequence[str], None] = '20d54449afc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlistvideos', sa.Column('listpath', sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlistvideos', 'listpath')
    # ### end Alembic commands ###
